name: Merge to Main

# on:
#   schedule:
#     - cron: '0 0 * * *' # 每天 0 点运行（可按需求调整）

# jobs:
#   merge:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Configure Git
#         run: |
#           git config --global user.name "yuuuuuj"
#           git config --global user.email "17373046129@163.com"

#       - name: Merge to Main
#         run: |
#           git checkout main
#           git merge feature
#           git push origin main
# name: Merge Feature to Main

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "yuuuuuj"
          git config --global user.email "17373046129@163.com"

      - name: Merge to Main
        run: |
          git checkout main
          git merge feature
          git push origin main
