name: Auto Merge Feature to Main

on:
  push:
    branches:
      - feature # 开发分支名称

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge to Main
        run: |
          git checkout remotes/origin/dev
          git pull
          git checkout -b feature-merge
