name: Merge on Push with Tests
on:
  push:
    branches:
      - feature

jobs:
  merge-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "yuuuuuj"
          git config --global user.email "17373046129@163.com"
          git remote set-url origin https://github.com/jiminmjh/Xtx-uniShop.git

      - name: Merge changes
        run: |
          git fetch
          git checkout main
          git merge feature --allow-unrelated-histories
          git push
