name: Merge to Main

on:
  schedule:
    - cron: '0 0 * * *' # 每天 0 点运行（可按需求调整）

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "your-username"
          git config --global user.email "your-email@example.com"

      - name: Merge to Main
        run: |
          git checkout main
          git merge your-branch-name
          git push origin main
