name: Merge on Push with Tests
on:
  push:
    branches:
      - feature

jobs:
  merge-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "yuuuuuj"
          git config --global user.email "17373046129@163.com"

      - name: Merge change
        run: |
          git pull
          git checkout main
          git merge feature
          git push
